version: '2.1'

services:
  live-reload:
    image: spotify-radio
    build: .
    environment:
      - PORT=3000
    command: 
    - npm
    - run
    - live-reload
    volumes:
      -  C:\Users\felip\codes\semana-js-expert:/spotify-radio/
      - C:\Users\felip\codes\semana-js-expert\node_modules:/spotify-radio/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules: {}